In [1]:
import numpy as np

In [2]:
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]

In [5]:
# Vamos a concatenarlos, quedan en una sola dimensión
np.concatenate([x, y, z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [8]:
# Vamos a probar en que eje lo queremos tener sería con index, que se concatenen en el eje 1
a = [[1, 2],
    [3, 4]]
b = [[5, 6],
    [7, 8]]

In [7]:
np.concatenate([a, b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [10]:
# Vamos a probar en que eje lo queremos tener sería con index, que se concatenen en el eje 0
np.concatenate([a, b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
# Cambiamos las forma del array
array_concatenado = np.concatenate([a, b], axis=0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
# Conocer la forma, 4 filas por 2 columnas
array_concatenado.shape

(4, 2)

In [15]:
# Podemos hacer que se reorganice, de 2 filas por 4 columnas
array_reformado = array_concatenado.reshape(2, 4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
# Sumar arrays
array_sumados = array_reformado + array_reformado
array_sumados

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [17]:
# Multiplicados arrays
array_multi = array_reformado * array_reformado
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [18]:
# Raiz cuadrada en arrays
array_raices = np.sqrt(array_multi)
array_raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [21]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
a

array([[1, 2],
       [3, 4]])

In [22]:
b

array([[5, 6],
       [7, 8]])

In [23]:
suma_AB = a + b
suma_AB

array([[ 6,  8],
       [10, 12]])

In [24]:
productoAB = a * b
productoAB

array([[ 5, 12],
       [21, 32]])