In [2]:
import numpy as np

In [6]:
# Array unidimensional
array1d = np.array([1,2,3,4,5])

In [12]:
# Array bidimensional
array2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [10]:
# Acceder a numero específicos por su índice en el array unidimensional
array1d[0]

np.int64(1)

In [9]:
array1d[-1]

np.int64(5)

In [22]:
# Acceder a numero específicos por su índice en el array bidimensional, obtiene el primer elemento que es la fila. Esto es
# indexación
array2d[0]

array([1, 2, 3])

In [15]:
# Solo obtener un número y no toda la fila
array2d[1][2]

np.int64(6)

In [17]:
# Otra forma de llegar el número buscado
array2d[1, 2]

np.int64(6)

In [19]:
# Usar slice en array unidimensional
array1d[1:4]

array([2, 3, 4])

In [24]:
# Usar slice en array bidimensional, 1 es la fila y : es que quiero toda la fila
array2[1, :]

array([4, 5, 6])

In [25]:
# Usar slice en array bidimensional, obtener los dos últimos número de la fila
array2[1, 1:3]

array([5, 6])

In [26]:
# Vamos a usar slice para obtener una columna completa
array2d[:, 1]

array([2, 5, 8])

In [33]:
# Vamos a usar slice para obtener los dos primeros número de las primeras dos filas
array2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [34]:
# indexación booleana, seleccionar elementos de un array que cumpla con algunas condicones
array1d > 3

array([False, False, False,  True,  True])

In [36]:
# Números pares
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])