In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Vemos que es de una sola dimensión, que tiene 9 filas
array.shape

(9,)

In [7]:
# Con este método podemos decirle a ese array de una dimensión, cómo quiero que sea, por ejemplo en este caso lo convertimos en
# un bidimensional
array_mod = array.reshape(3, 3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array_mod2 = array.reshape(-1, 3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Voltear el array, de filas a columnas y de columnas a filas
array_volteado = array_mod2.transpose()
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
# Convertir un arrat multidimensional a unidimensional. Este crea una copia aplanada
array_chato = array_mod.flatten()
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Es lo mismo pero no crea una copia
array_ravel = array_mod.ravel()
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])