In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
array2 = np.array([[0], [10], [20], [30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [7]:
# Broadcasting, extender operaciones. Vamos a sumar los arrays que tienen diferente forma
broadcast_suma = array1 + array2
broadcast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
broadcast_multi = array1 * array2
broadcast_multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [9]:
# Funciones universales en NumPy, se aplica vectorizada
a = np.array([1,2,3])
b = np.array([4,5,6])

In [12]:
# Nos devuelve un solo array de la suma
resultado = np.add(a, b)
resultado

array([5, 7, 9])

In [14]:
# Nos devuelve un solo array de la resta
resultado = np.subtract(a, b
resultado

array([-3, -3, -3])

In [15]:
# Nos devuelve un solo array de la multiplicación
resultado = np.multiply(a, b)
resultado

array([ 4, 10, 18])

In [16]:
# Nos devuelve un solo array de la división
resultado = np.divide(a, b)
resultado

array([0.25, 0.4 , 0.5 ])

In [17]:
# Funciones matemáticas universales, conocer el exponencial
resultado2 = np.exp(a)
resultado2

array([ 2.71828183,  7.3890561 , 20.08553692])

In [18]:
# Funciones matemáticas universales, conocer el logaritmo natural
resultado3 = np.log(a)
resultado3

array([0.        , 0.69314718, 1.09861229])

In [20]:
resultado4 = np.log10(a)
resultado4

array([0.        , 0.30103   , 0.47712125])

In [21]:
# Funciones matemáticas universales, conocer la raíz cuadrada
resultado5 = np.sqrt(a)
resultado5

array([1.        , 1.41421356, 1.73205081])