In [3]:
import numpy as np

In [5]:
# Crear un array con un dato faltente, esto nos permite reservar un espacio
array = np.array([1, 2, np.nan, 4, 5])
array

array([ 1.,  2., nan,  4.,  5.])

In [6]:
# Cómo ver que hay un nan
np.isnan(array)

array([False, False,  True, False, False])

In [8]:
# Cómo manejar nuestros elementos no válidos, el promedio no se puede sacar porque tiene valores nan
np.mean(array)

np.float64(nan)

In [9]:
# Funciones que ignoran números no válidos
np.nanmean(array)

np.float64(3.0)

In [10]:
# Sustituir los valores no válidos, se usa mucho
array_con_0 = np.where(np.isnan(array), 0, array)
array_con_0

array([1., 2., 0., 4., 5.])

In [11]:
# Reemplazar con un primedio
promedio = np.nanmean(array)
array_con_promedio = np.where(np.isnan(array), promedio, array)
array_con_promedio

array([1., 2., 3., 4., 5.])

In [14]:
# Cómo eliminar datos faltantes. La tílde invertida ~ hace que muestre el array completo sin el nan, porque si lo dejamos sin eso muestra
# el nan y eso no es lo que queremos eliminar, porque si muestra el nan quiere decir que eliminamos los números.
array_filtrado = array[~np.isnan(array)]
array_filtrado

array([1., 2., 4., 5.])

In [15]:
array = np.array([3, np.nan, 7, np.nan, 0, 4.5, np.nan])

sustituir_nans = np.where(np.isnan(array), 0, array)
sustituir_nans

array([3. , 0. , 7. , 0. , 0. , 4.5, 0. ])