In [14]:
import numpy as np

In [15]:
ruta = r"C:\Users\Hogar\Desktop\Python-DataScience-y-Machine-Learning\Recursos\medallas1.csv"

In [16]:
array = np.genfromtxt(ruta)
array

ValueError: Some errors were detected !
    Line #15 (got 2 columns instead of 1)
    Line #17 (got 2 columns instead of 1)
    Line #20 (got 2 columns instead of 1)
    Line #22 (got 2 columns instead of 1)
    Line #24 (got 2 columns instead of 1)
    Line #27 (got 4 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #39 (got 3 columns instead of 1)
    Line #44 (got 4 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #65 (got 2 columns instead of 1)
    Line #70 (got 2 columns instead of 1)
    Line #72 (got 3 columns instead of 1)
    Line #73 (got 3 columns instead of 1)
    Line #74 (got 4 columns instead of 1)
    Line #77 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #82 (got 2 columns instead of 1)
    Line #86 (got 3 columns instead of 1)

In [19]:
# Esto se hace para delimitarlos por , ya que es un archivo csv y si no se hace da un error por en la linea anterior
array = np.genfromtxt(ruta, delimiter=',')
array

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,   1.,   2.,   3.,  nan],
       [ nan,   2.,   2.,   4.,  nan],
       [ 17.,   7.,  22.,  46.,  nan],
       [  1.,   1.,   5.,   7.,  nan],
       [ nan,   3.,   4.,   7.,  nan],
       [  2.,  nan,  nan,   2.,  nan],
       [ nan,   1.,  nan,   1.,  nan],
       [  1.,   3.,   3.,   7.,  nan],
       [  3.,   1.,   3.,   7.,  nan],
       [  1.,  nan,  nan,   1.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,   8.,  21.,  nan],
       [  3.,   1.,   2.,   6.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,  11.,  24.,  nan],
       [  2.,   4.,   6.,  12.,  nan],
       [ nan,   4.,   1.,   5.,  nan],
       [  3.,   3.,   2.,   8.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   3.,   5.,  15.,  nan],
       [  4.,   4.,   3.,  11.,  nan],
       [  3.,   4.,   4.,  11.,  nan],
       [ nan,   3.,   2.,   5.,  nan],
       [  2.,   1.,  nan,   3.,  nan],
       [  1.,   1.,   4.,

In [22]:
# Ya vismo anteriormente que los espacios son nan, pero no los queremos de esa forma, entonces los llevamos a cero
array = np.genfromtxt(ruta, delimiter=',', filling_values=0)
array

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,

In [23]:
# Vamos a eliminar ignorando los encabezados de la columna
array = np.genfromtxt(ruta, delimiter=',', filling_values=0, skip_header=1)
array

array([[  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,   6.,   0.],
       [ 39.,  41.,  33.,

In [24]:
# Cambiar a integer
array = np.genfromtxt(ruta, delimiter=',', filling_values=0, skip_header=1, dtype=int)
array

array([[  0,   1,   2,   3,   0],
       [  0,   2,   2,   4,   0],
       [ 17,   7,  22,  46,   0],
       [  1,   1,   5,   7,   0],
       [  0,   3,   4,   7,   0],
       [  2,   0,   0,   2,   0],
       [  0,   1,   0,   1,   0],
       [  1,   3,   3,   7,   0],
       [  3,   1,   3,   7,   0],
       [  1,   0,   0,   1,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,   8,  21,   0],
       [  3,   1,   2,   6,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,  11,  24,   0],
       [  2,   4,   6,  12,   0],
       [  0,   4,   1,   5,   0],
       [  3,   3,   2,   8,   0],
       [  0,   0,   1,   1,   0],
       [  7,   3,   5,  15,   0],
       [  4,   4,   3,  11,   0],
       [  3,   4,   4,  11,   0],
       [  0,   3,   2,   5,   0],
       [  2,   1,   0,   3,   0],
       [  1,   1,   4,   6,   0],
       [ 39,  41,  33, 113,   0],
       [  1,   0,   1,   2,   0],
       [  1,   1,   2,   4,   0],
       [  1,   0,   1,   2,   0],
       [  0,  

In [26]:
# Exportar un archivo
array_ejemplo = np.array([[1,2,3],
                        [4,5,6]])

In [28]:
ruta = r"C:\Users\Hogar\Desktop\Python-DataScience-y-Machine-Learning\Recursos\mi_array.csv"

In [30]:
np.savetxt(ruta, array_ejemplo, delimiter=',', fmt='%d')